### ISSUE TITLE
Telegram Bot failure

### ISSUE THREAD

**Issue by kyberorg** [kyberorg/axe#219]
```
2020-10-14 09:26:40.783 ERROR 6 --- [gram Connection] o.t.t.u.DefaultBotSession                : Error getting updates

org.telegram.telegrambots.meta.exceptions.TelegramApiRequestException: Error getting updates

	at org.telegram.telegrambots.meta.api.methods.updates.GetUpdates.deserializeResponse(GetUpdates.java:118) ~[telegrambots-meta-4.6.jar!/:na]

	at org.telegram.telegrambots.updatesreceivers.DefaultBotSession$ReaderThread.getUpdatesFromServer(DefaultBotSession.java:263) ~[telegrambots-4.6.jar!/:na]

	at org.telegram.telegrambots.updatesreceivers.DefaultBotSession$ReaderThread.run(DefaultBotSession.java:194) ~[telegrambots-4.6.jar!/:na]
```

Should be fixed by updating Telegrambots.
Also Telegrambots version `5.0.1` requires adaptation.

- [ ] Adapt Telegrambots version `5.0.1`

**Comment by kyberorg** [comment]
This error occurs when two instances attempt to use same API key. Solved by regenerating Bot API key. 
Most probably re-occur when we attempt to launch 1+ contianers.

**Comment by kyberorg** [comment]
Adaptation will be part of #259
