### ISSUE TITLE
Healthcheck SSL problem

### ISSUE THREAD

**Issue by kyberorg** [kyberorg/axe#261]
```
Tech message: unable to find valid certification path to requested target,
2020-12-22 08:34:50.289 ERROR 8 --- [nio-8080-exec-6] eu.yals.utils.YalsErrorKeeper            : [YalsErrorKeeper] === Error ===,
2020-12-22 08:34:50.288  INFO 8 --- [nio-8080-exec-6] eu.yals.controllers.YalsErrorController  : [YalsErrorController] Status: 500. Path: /actuator/health. Exception message: Request processing failed; nested exception is kong.unirest.UnirestException: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target,
	at eu.yals.utils.YalsHealthIndicator.isMainPageAccessible(YalsHealthIndicator.java:68) ~[classes!/:2.7.4],
	at eu.yals.utils.YalsHealthIndicator.health(YalsHealthIndicator.java:50) ~[classes!/:2.7.4]

```

**Comment by kyberorg** [comment]
It was temporary error due to misconfiguration (used qa.yals.eu instead of demo.yals.eu)
