### ISSUE TITLE
H2 support after updating to `2.0.22`

### ISSUE THREAD

**Issue by kyberorg** [kyberorg/axe#626]
Security fix in #625 broke Application. So H2 is no works.

```
	at io.kyberorg.yalsee.services.LinkService.createLink(LinkService.java:189) ~[classes!/:edge]
	at io.kyberorg.yalsee.ui.HomeView.saveLink(HomeView.java:349) ~[classes!/:edge]
	at io.kyberorg.yalsee.ui.HomeView.onSaveLink(HomeView.java:326) ~[classes!/:edge]
	at io.kyberorg.yalsee.ui.HomeView$$Lambda$1522/0x0000000000000000.onComponentEvent(Unknown Source) ~[na:na]
...
Caused by: org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: NULL not allowed for column "ID"; SQL statement:
insert into links (id, ident, link) values (null, ?, ?) [23502-202]
```

**Comment by kyberorg** [comment]
H2 support discontinued
